package logic.network;

public enum MessageType {
    CLOSE_CONNECTION_BY_CLIENT,
    CONNECTION_CLOSED_BY_ADMIN,
    OK,
    USERNAME,
    PLAYERS,
    COLOR_CHANGED,
    BOT_ADDED,
    MAP_CHANGED,
    PLAYER_DELETED,
    START_GAME,
    REINFORCE,
    ATTACK,
    FORTIFY,
    END_REINFORCE,
    END_ATTACK,
    END_FORTIFY,
    GAME_OVER,
    PLAYER_LEFT_IN_GAME,
    CONNECTION_ERROR,
    SERVER_CLOSED_ERROR,
    GAME_STARTED_ERROR,
    DUPLICATE_NAME_ERROR,
    MAX_PLAYERS_ERROR,
    INVALID_NAME_ERROR
}
