package logic.network;

public enum MessageType {
    CLOSE_CONNECTION_BY_CLIENT,
    DUPLICATE_NAME_ERROR,
    OK,
    USERNAME,
    MAX_PLAYERS_ERROR,
    PLAYERS,
    COLOR_CHANGED,
    BOT_ADDED,
    CONNECTION_CLOSED_BY_ADMIN,
    PLAYER_DELETED,
    INVALID_NAME,
    START_GAME,
    REINFORCE,
    ATTACK,
    FORTIFY,
    END_REINFORCE,
    END_ATTACK,
    END_FORTIFY,
    GAME_OVER,
    PLAYER_LEFT_IN_GAME,
    CONNECTION_ERROR,
    SERVER_CLOSED_ERROR,
    MAP_CHANGED,
    GAME_STARTED_ERROR
}
